name: Deploy Game Server

on:
  push:
    branches:
      - main  # 监听 main 分支的提交

jobs:
  deploy:
    runs-on: ubuntu-latest  # 运行环境（Linux 服务器）
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # 下载代码

      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.19  # 选择 Go 版本

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libasound2-dev pkg-config libx11-dev libxcursor-dev

      - name: Download Go Modules
        run: |
          go mod tidy
          go mod download

      - name: Build Game Server
        run: |
          go build -o game main.go  # 编译 Go 服务器
          chmod +x game  # 赋予执行权限

      - name: Run Game Server
        run: ./game  # 运行游戏服务器
